export const FORMULARIO_PRODUCTO = 'FORMULARIO_PRODUCTO';
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const AGREGAR_PRODUCTOS = 'AGREGAR_PRODUCTOS';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PRODUCTO_ACTUAL = 'PRODUCTO_ACTUAL';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const PRODUCTO_ERROR = 'PRODUCTO_ERROR';

export const TAREAS_PRODUCTO = 'TAREAS_PRODUCTO';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
export const LIMPIAR_TAREA ='LIMPIAR_TAREA';

export const MOSTRAR_ALERTA ='MOSTRAR_ALERTA';
export const OCULTAR_ALERTA ='OCULTAR_ALERTA';

export const REGISTRO_EXITOSO ='REGISTRO_EXITOSO';
export const REGISTRO_ERROR ='REGISTRO_ERROR';
export const OBTENER_USUARIO ='OBTENER_USUARIO';
export const LOGIN_EXITOSO ='LOGIN_EXITOSO';
export const LOGIN_ERROR ='LOGIN_ERROR';
export const CERRAR_SESION ='CERRAR_SESION';